# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: OzLevi.PCDoctor
PackageVersion: 1.0.1
InstallerType: portable
Commands:
  - pcdoctor
ReleaseDate: 2026-09-29
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/ozlevi29/Analyzing-files-on-the-computer/releases/download/v1.0.1/PCDoctor.exe
    InstallerSha256: CE2D626F4E29EB2A573E49101574736E5F21D49B8575E002A48906C6E22C9C1D
ManifestType: installer
ManifestVersion: 1.6.0
